import Navbar from "./common/navbar/Navbar";
import { Anybody } from "next/font/google";
import './globals.css'

const anybody = Anybody({
  display:'swap',
  subsets:['latin'],
  weight:"400"
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={anybody.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
